---
  - name: Install HTTPD
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "Fedora" or ansible_distribution == "Amazon"

  - name: start up HTTPD
    service: 
      name: httpd
      state: started
    when: ansible_distribution == "Fedora" or ansible_distribution == "Amazon"

  - name: Enable HTTPD
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "Fedora" or ansible_distribution == "Amazon"


  - name: update package cache
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu" ansible_distribution == "Debian"

  - name: start up apache service
    service: 
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu" ansible_distribution == "Debian"

  - name: Enable apache2
    service: 
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu" ansible_distribution == "Debian"
