# single play
---
- name: Install Apache on ubuntu server
  become: yes
  hosts: ubuntu
  

  tasks:
  - name: update package cache
    apt:
      update_cache: yes

  - name: Install apache2
    apt:
      name: apache2
      state: present

  - name: start up apache service
    service: 
      name: apache2
      state: started

  - name: Enable apache2
    service: 
      name: apache2
      enabled: yes

...
